#!/usr/bin/env ruby
#^syntax detection

site "https://galaxy.ansible.com/api/v1"

role "mi11er.apt",
  git: "git@bitbucket.org:mi11er/ansible-role-apt.git"
role "mi11er.ufw",
  git: "git@bitbucket.org:mi11er/ansible-role-ufw.git"
role "mi11er.ssh",
  git: "git@bitbucket.org:mi11er/ansible-role-ssh.git"
role "mi11er.postfix",
  git: "git@bitbucket.org:mi11er/ansible-role-postfix.git"
role "mi11er.logs",
  git: "git@bitbucket.org:mi11er/ansible-role-logs.git"
role "mi11er.opendkim",
  git: "git@bitbucket.org:mi11er/ansible-role-opendkim.git"
